import type { ClientPortalConfig } from '../types'

const EDGE_CITY: ClientPortalConfig = {
  slug: 'edge-city',
  clientName: 'Edge City Builders',
  portalTitle: 'Staff Uniform Portal',
  logoText: 'EDGE CITY',
  accentColor: '#f5a623',
  hero: {
    tagline: 'Your uniform programme.',
    subtitle: 'Order approved staff kit — simple, fast, controlled.',
  },
  categories: [
    {
      id: 'site-safety',
      slug: 'site-safety',
      name: 'Site Safety',
      description: 'Hi-vis and safety-rated garments for all on-site crew.',
      image: '/cat-jacket.jpg',
      products: [
        {
          id: 'hivi-polo',
          slug: 'hivi-polo',
          name: 'Hi-Vis Polo',
          categoryId: 'site-safety',
          description:
            'Class 2 hi-vis polo with moisture-wicking fabric and Edge City embroidered chest logo. Mandatory for all site crew.',
          image: '/cat-overshirt.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [
            { name: 'Yellow', hex: '#f5d020' },
            { name: 'Orange', hex: '#f5a623' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 5500,
          requiresStaffName: false,
          sku: 'ECB-HIVI-POLO',
        },
        {
          id: 'hivi-tee',
          slug: 'hivi-tee',
          name: 'Hi-Vis Tee',
          categoryId: 'site-safety',
          description:
            'Lightweight Class 1 hi-vis tee. Cotton/poly blend. Ideal for summer site work.',
          image: '/cat-tee-heavy.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [{ name: 'Yellow', hex: '#f5d020' }],
          decorationMethod: 'Screen Print',
          leadWeeks: [2, 3],
          priceCents: 4200,
          requiresStaffName: false,
          sku: 'ECB-HIVI-TEE',
        },
        {
          id: 'wet-weather-jacket',
          slug: 'wet-weather-jacket',
          name: 'Wet Weather Jacket',
          categoryId: 'site-safety',
          description:
            'Waterproof outer shell with sealed seams and hi-vis panels. Full zip with embroidered chest logo.',
          image: '/cat-jacket.jpg',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [{ name: 'Yellow/Navy', hex: '#f5d020' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [4, 6],
          priceCents: 12000,
          requiresStaffName: false,
          sku: 'ECB-WET-JACKET',
        },
      ],
    },
    {
      id: 'everyday-staff',
      slug: 'everyday-staff',
      name: 'Everyday Staff',
      description: 'Branded workwear for daily use across all roles.',
      image: '/cat-hoodie.jpg',
      products: [
        {
          id: 'polo',
          slug: 'polo',
          name: 'Staff Polo',
          categoryId: 'everyday-staff',
          description:
            'Pique cotton/poly polo with Edge City embroidered chest logo. Available in navy and charcoal.',
          image: '/cat-overshirt.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [
            { name: 'Navy', hex: '#1a2740' },
            { name: 'Charcoal', hex: '#3d3d3d' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 4800,
          requiresStaffName: false,
          sku: 'ECB-POLO',
        },
        {
          id: 'tee',
          slug: 'tee',
          name: 'Staff Tee',
          categoryId: 'everyday-staff',
          description:
            'Heavyweight cotton tee with Edge City screen-printed back graphic. Everyday wear.',
          image: '/cat-tee-heavy.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [
            { name: 'Black', hex: '#080808' },
            { name: 'Navy', hex: '#1a2740' },
          ],
          decorationMethod: 'Screen Print',
          leadWeeks: [2, 3],
          priceCents: 3800,
          requiresStaffName: false,
          sku: 'ECB-TEE',
        },
        {
          id: 'hoodie',
          slug: 'hoodie',
          name: 'Staff Hoodie',
          categoryId: 'everyday-staff',
          description:
            'Midweight fleece hoodie with embroidered chest logo and printed back graphic. Site and office appropriate.',
          image: '/cat-hoodie.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
          colours: [
            { name: 'Black', hex: '#080808' },
            { name: 'Navy', hex: '#1a2740' },
          ],
          decorationMethod: 'Embroidery + Print',
          leadWeeks: [3, 5],
          priceCents: 6500,
          requiresStaffName: false,
          sku: 'ECB-HOODIE',
        },
        {
          id: 'trucker-cap',
          slug: 'trucker-cap',
          name: 'Trucker Cap',
          categoryId: 'everyday-staff',
          description:
            'Structured trucker cap with embroidered Edge City logo on front panel.',
          image: '/cat-cap.jpg',
          sizes: ['One Size'],
          colours: [
            { name: 'Black/White', hex: '#080808' },
            { name: 'Navy/Khaki', hex: '#1a2740' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 3200,
          requiresStaffName: false,
          sku: 'ECB-CAP',
        },
      ],
    },
    {
      id: 'office-management',
      slug: 'office-management',
      name: 'Office & Management',
      description: 'Premium corporate range for office and management staff.',
      image: '/cat-overshirt.jpg',
      products: [
        {
          id: 'business-polo',
          slug: 'business-polo',
          name: 'Business Polo',
          categoryId: 'office-management',
          description:
            'Premium pique polo in a tailored fit. Subtle embroidered chest logo. Office and client-facing appropriate.',
          image: '/cat-overshirt.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
          colours: [
            { name: 'Navy', hex: '#1a2740' },
            { name: 'White', hex: '#f5f5f0' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 5],
          priceCents: 5800,
          requiresStaffName: true,
          sku: 'ECB-BIZ-POLO',
        },
        {
          id: 'softshell',
          slug: 'softshell',
          name: 'Softshell Jacket',
          categoryId: 'office-management',
          description:
            'Stormtech softshell with embroidered chest logo. Waterproof-treated. Site visit and office appropriate.',
          image: '/cat-jacket.jpg',
          sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
          colours: [
            { name: 'Navy', hex: '#1a2740' },
            { name: 'Black', hex: '#080808' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [4, 6],
          priceCents: 14000,
          requiresStaffName: true,
          sku: 'ECB-SOFTSHELL',
        },
      ],
    },
    {
      id: 'accessories',
      slug: 'accessories',
      name: 'Accessories',
      description: 'Branded accessories and extras to complete the kit.',
      image: '/cat-bottle.jpg',
      products: [
        {
          id: 'drink-bottle',
          slug: 'drink-bottle',
          name: 'Drink Bottle',
          categoryId: 'accessories',
          description:
            'Stainless steel 600ml bottle with Edge City printed logo. Keeps cold 24hr, hot 12hr.',
          image: '/cat-bottle.jpg',
          sizes: ['One Size'],
          decorationMethod: 'Laser Engrave / Print',
          leadWeeks: [3, 5],
          priceCents: 2800,
          requiresStaffName: false,
          sku: 'ECB-BOTTLE',
        },
        {
          id: 'structured-cap',
          slug: 'structured-cap',
          name: 'Structured Cap',
          categoryId: 'accessories',
          description:
            '6-panel structured cap with embroidered Edge City logo. Retail-quality finish.',
          image: '/cat-cap.jpg',
          sizes: ['S/M', 'L/XL'],
          colours: [
            { name: 'Black', hex: '#080808' },
            { name: 'Navy', hex: '#1a2740' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 3200,
          requiresStaffName: false,
          sku: 'ECB-STRUCT-CAP',
        },
      ],
    },
  ],
  ordering: {
    requiresStaffName: false,
    requiresDeliveryAddress: false,
    deliveryOptions: [
      {
        id: 'head-office',
        label: 'Head Office — Auckland CBD',
        address: '1 Main St, Auckland, 1010',
      },
      {
        id: 'south-site',
        label: 'South Site — Manukau',
        address: '45 Industry Rd, Manukau, 2104',
      },
    ],
    orderNote:
      'All items are pre-approved. Orders are processed within 2 business days. For urgent requests contact your Tendencies account manager.',
  },
  contact: {
    manager: 'Ben',
    email: 'ben@tendencies.co.nz',
    phone: '+64 21 XXX XXXX',
  },
  emails: {
    internalTo: 'ben@tendencies.co.nz',
  },
}

export default EDGE_CITY
