// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit by hand.
// Run: npm run import:edge-city
// Source: data/edge-city-products.csv (or .xlsx)
// Generated: 2026-05-19T05:53:45.585Z
// ─────────────────────────────────────────────────────────────────────────────

import type { PortalCategory, PortalProduct, PortalFeaturedCollection } from '../types'

export const EDGE_CITY_PRODUCTS: PortalProduct[] = [
  {
    id: "zh135",
    slug: "zh135",
    sku: "ZH135",
    name: "Streetworx Tee",
    categoryId: "tees-polos",
    description: "Lightweight cotton tee with modern slim fit and longer curved hem. Available in three colourways.",
    image: "/edge-city/syzmik-ZH135-hero.png",
    images: ["/edge-city/syzmik-ZH135-charcoal.png", "/edge-city/syzmik-ZH135-navy.png", "/edge-city/syzmik-ZH135-petrol-blue.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Navy" },
        { name: "Petrol Blue" },
        { name: "Charcoal Marle" },
      ],
    decorationMethod: "Screen Print",
    leadWeeks: [2, 2],
    priceCents: 2800,
    requiresStaffName: false,
  },
  {
    id: "zh239",
    slug: "zh239",
    sku: "ZH239",
    name: "Hi Vis Squad Singlet",
    categoryId: "hi-vis-essentials",
    description: "Class D/N rated hi-vis singlet. 100% polyester 175 GSM. Moisture-wicking mesh panels for maximum breathability on hot days.",
    image: "/edge-city/syzmik-hi-vis-ZH239-hero.png",
    images: ["/edge-city/syzmik-hi-vis-ZH239-front.png", "/edge-city/syzmik-hi-vis-ZH239-back.png"],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Yellow/Navy" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 3500,
    requiresStaffName: false,
  },
  {
    id: "zh320",
    slug: "zh320",
    sku: "ZH320",
    name: "Syzmik Hi Vis Polo",
    categoryId: "hi-vis-essentials",
    description: "Class D/N rated hi-vis polo. Moisture management fabric, taped seams, vented back. Staff name embroidered on chest.",
    image: "/edge-city/syzmik-hi-vis-zh320-hero.png",
    images: ["/edge-city/syzmik-hi-vis-zh320-front.png", "/edge-city/syzmik-hi-vis-zh320-back.png"],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Yellow/Navy" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 6500,
    requiresStaffName: true,
  },
  {
    id: "zh415",
    slug: "zh415",
    sku: "ZH415",
    name: "Syzmik Hi Vis Spliced Polo",
    categoryId: "hi-vis-essentials",
    description: "Class D/N hi-vis polo with contrast splicing panels. Moisture management, underarm gussets for full mobility. Staff name embroidered on chest.",
    image: "/edge-city/syzmik-hi-vis-zh415-hero.png",
    images: ["/edge-city/syzmik-hi-vis-zh415-front.png", "/edge-city/syzmik-hi-vis-zh415-back.png"],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Yellow/Navy" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 7500,
    requiresStaffName: true,
  },
  {
    id: "zh731",
    slug: "zh731",
    sku: "ZH731",
    name: "Syzmik Womens Hi Vis Polo",
    categoryId: "hi-vis-essentials",
    description: "Class D/N rated women's fit hi-vis polo. Shaped cut, moisture management fabric, vented back. Staff name embroidered on chest.",
    image: "/edge-city/syzmik-hi-vis-zh731.png",
    sizes: ["8", "10", "12", "14", "16", "18", "20", "22", "24"],
    colours: [
        { name: "Yellow/Navy" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 6500,
    requiresStaffName: true,
  },
  {
    id: "p200ms",
    slug: "p200ms",
    sku: "P200MS",
    name: "Balance Short Sleeve Polo",
    categoryId: "tees-polos",
    description: "100% polyester sports interlock. UPF Rating 50+. 155 GSM. Staff name embroidered on chest.",
    image: "/edge-city/fashion-biz-p200ms-hero.png",
    images: ["/edge-city/fashion-biz-p200ms-navy-white-front.png", "/edge-city/fashion-biz-p200ms-navy-white-back.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Navy/Sky" },
        { name: "Navy/Red" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 5500,
    requiresStaffName: false,
  },
  {
    id: "1321",
    slug: "1321",
    sku: "1321",
    name: "Portsea Polo",
    categoryId: "tees-polos",
    description: "Cotton-back polyester polo. 80% polyester / 20% cotton. 180 GSM. Smart appearance for site or office.",
    image: "/edge-city/portsea-1321-front.png",
    images: ["/edge-city/portsea-1321-back.png", "/edge-city/portsea-1321-slate-black.png"],
    sizes: ["8", "10", "12", "14", "16", "18", "20", "22", "24"],
    colours: [
        { name: "Navy/White" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 5800,
    requiresStaffName: false,
  },
  {
    id: "zs235",
    slug: "zs235",
    sku: "ZS235",
    name: "Essential Stretch Cargo Short",
    categoryId: "site-shorts",
    description: "98% Cotton 2% Elastane 280 GSM. Reinforced seat, multiple cargo pockets. Waist sizes in cm.",
    image: "/edge-city/syzmik-shorts-zs235-khaki.png",
    images: ["/edge-city/syzmik-shorts-zs235-navy.png"],
    sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
    colours: [
        { name: "Navy" },
        { name: "Khaki" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 8500,
    requiresStaffName: false,
  },
  {
    id: "zs607",
    slug: "zs607",
    sku: "ZS607",
    name: "Rugged Cooling Stretch Short",
    categoryId: "site-shorts",
    description: "98% Cotton 2% Elastane Square Weave Cotton Ripstop 240 GSM. Superior durability for demanding sites.",
    image: "/edge-city/ZS607-hero.png",
    images: ["/edge-city/ZS607-navy.png", "/edge-city/ZS607-khaki.png", "/edge-city/ZS607-black.png"],
    sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
    colours: [
        { name: "Navy" },
        { name: "Khaki" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 9500,
    requiresStaffName: false,
  },
  {
    id: "zs735",
    slug: "zs735",
    sku: "ZS735",
    name: "Womens Essential Stretch Cargo Short",
    categoryId: "site-shorts",
    description: "Women's cut stretch cargo shorts with cooling vents. Reinforced seat, multiple cargo pockets. Waist in cm.",
    image: "/edge-city/syzmik-shorts-zs735-khaki.png",
    images: ["/edge-city/syzmik-shorts-zs735-navy.png"],
    sizes: ["6", "8", "10", "12", "14", "16", "18", "20", "22", "24"],
    colours: [
        { name: "Khaki" },
        { name: "Navy" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 8500,
    requiresStaffName: false,
  },
  {
    id: "zp604",
    slug: "zp604",
    sku: "ZP604",
    name: "Rugged Cooling Stretch Pant",
    categoryId: "site-pants",
    description: "98% Cotton 2% Elastane Square Weave Cotton Ripstop 240 GSM. Reinforced knees, multiple pockets, durable seams for tough jobs.",
    image: "/edge-city/syzmik-pants-ZP604-hero.png",
    images: ["/edge-city/syzmik-pants-ZP604-navy.png", "/edge-city/syzmik-pants-ZP604-khaki.png", "/edge-city/syzmik-pants-ZP604-navy-back.png", "/edge-city/syzmik-pants-ZP604-khaki-back.png"],
    sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
    colours: [
        { name: "Navy" },
        { name: "Khaki" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 12800,
    requiresStaffName: false,
  },
  {
    id: "zp444",
    slug: "zp444",
    sku: "ZP444",
    name: "Streetworx Comfort Pant",
    categoryId: "site-pants",
    description: "67% Cotton 31% Polyester 2% Spandex 280 GSM. Contemporary stretch work trousers with room to move.",
    image: "/edge-city/syzmik-pants-ZP444-navy.png",
    images: ["/edge-city/syzmik-pants-ZP444-navy-back.png"],
    sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
    colours: [
        { name: "Navy" },
      ],
    decorationMethod: "None",
    leadWeeks: [2, 2],
    priceCents: 11500,
    requiresStaffName: false,
  },
  {
    id: "zt467",
    slug: "zt467",
    sku: "ZT467",
    name: "Multi-Pocket Hoodie",
    categoryId: "hoodies-midlayers",
    description: "55% Cotton 45% Polyester 320 GSM. Hi-vis rated warm hoodie. Multiple pockets, drawstring hood, kangaroo pocket.",
    image: "/edge-city/syzmik-hoodie-zt467-hero.png",
    images: ["/edge-city/syzmik-hoodie-zt467-back.png", "/edge-city/syzmik-hoodie-Charcoal-Black.png", "/edge-city/syzmik-hoodie-Slate-Charcoal.jpeg", "/edge-city/syzmik-hoodie-zt467-navy-charcoal.jpeg"],
    sizes: ["XXS", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Charcoal/Black" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 9500,
    requiresStaffName: true,
  },
  {
    id: "zt867",
    slug: "zt867",
    sku: "ZT867",
    name: "Hi Vis Water Resistant Hoodie",
    categoryId: "hoodies-midlayers",
    description: "100% Polyester Fleece 320 GSM. Segmented reflective tape. Lightweight water resistant shell with warm soft fleece lining.",
    image: "/edge-city/syzmik-hi-vis-zt867.png",
    images: ["/edge-city/syzmik-hi-vis-zt867-front.png"],
    sizes: ["XXS", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Yellow" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 9500,
    requiresStaffName: false,
  },
  {
    id: "xth",
    slug: "xth",
    sku: "XTH",
    name: "XT Performance Pullover Hoodie",
    categoryId: "hoodies-midlayers",
    description: "270 GSM 100% polyester performance fabric. Smart site hoodie for project managers and office-to-site transitions.",
    image: "/edge-city/cloke-hoodie-xth-back-aqua-front.png",
    images: ["/edge-city/cloke-hoodie-xth-black-aqua-back.png", "/edge-city/cloke-hoodie-xth-navy-grey.png", "/edge-city/cloke-hoodie-xth-navy-white.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Navy/Grey" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 8000,
    requiresStaffName: false,
  },
  {
    id: "115740",
    slug: "115740",
    sku: "115740",
    name: "Bondi Bucket Hat",
    categoryId: "headwear",
    description: "Premium cotton twill bucket hat with white trim and sweatband. Embroidered club branding.",
    image: "/edge-city/trends-bucket-115740-3.png",
    images: ["/edge-city/trends-bucket-115740-4.png"],
    sizes: ["One Size"],
    colours: [
        { name: "White Sandwich Trim" },
        { name: "Navy" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 2400,
    requiresStaffName: false,
  },
  {
    id: "126398",
    slug: "126398",
    sku: "126398",
    name: "Faded Trucker Cap",
    categoryId: "headwear",
    description: "Structured five panel trucker hat with stylish faded finish. Embroidered logo on front panel.",
    image: "/edge-city/trends-trucker-126398-2.png",
    images: ["/edge-city/trends-trucker-126398-4.png"],
    sizes: ["One Size"],
    colours: [
        { name: "Navy" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 2200,
    requiresStaffName: false,
  },
  {
    id: "1174",
    slug: "1174",
    sku: "1174",
    name: "Nylon Bucket Hat",
    categoryId: "headwear",
    description: "Nylon wide brim bucket hat. Lightweight and packable. Ideal for sun protection on site.",
    image: "/edge-city/as-colour-1174-hero.png",
    images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png", "/edge-city/as-colour-1174-khaki.png"],
    sizes: ["One Size"],
    colours: [
        { name: "Navy" },
        { name: "Black" },
        { name: "Khaki" },
      ],
    decorationMethod: "Embroidery",
    leadWeeks: [2, 2],
    priceCents: 4800,
    requiresStaffName: false,
  },
]

export const EDGE_CITY_CATEGORIES: PortalCategory[] = [
  {
    id: "hi-vis-essentials",
    slug: "hi-vis-essentials",
    name: "Hi-Vis Essentials",
    description: "Class D/N rated high-visibility wear. Meet site safety standards on day one.",
    image: "/edge-city/syzmik-hi-vis-zh320-hero.png",
    products: [
      {
        id: "zh239",
        slug: "zh239",
        sku: "ZH239",
        name: "Hi Vis Squad Singlet",
        categoryId: "hi-vis-essentials",
        description: "Class D/N rated hi-vis singlet. 100% polyester 175 GSM. Moisture-wicking mesh panels for maximum breathability on hot days.",
        image: "/edge-city/syzmik-hi-vis-ZH239-hero.png",
        images: ["/edge-city/syzmik-hi-vis-ZH239-front.png", "/edge-city/syzmik-hi-vis-ZH239-back.png"],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Yellow/Navy" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 3500,
        requiresStaffName: false,
      },
      {
        id: "zh320",
        slug: "zh320",
        sku: "ZH320",
        name: "Syzmik Hi Vis Polo",
        categoryId: "hi-vis-essentials",
        description: "Class D/N rated hi-vis polo. Moisture management fabric, taped seams, vented back. Staff name embroidered on chest.",
        image: "/edge-city/syzmik-hi-vis-zh320-hero.png",
        images: ["/edge-city/syzmik-hi-vis-zh320-front.png", "/edge-city/syzmik-hi-vis-zh320-back.png"],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Yellow/Navy" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 6500,
        requiresStaffName: true,
      },
      {
        id: "zh415",
        slug: "zh415",
        sku: "ZH415",
        name: "Syzmik Hi Vis Spliced Polo",
        categoryId: "hi-vis-essentials",
        description: "Class D/N hi-vis polo with contrast splicing panels. Moisture management, underarm gussets for full mobility. Staff name embroidered on chest.",
        image: "/edge-city/syzmik-hi-vis-zh415-hero.png",
        images: ["/edge-city/syzmik-hi-vis-zh415-front.png", "/edge-city/syzmik-hi-vis-zh415-back.png"],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Yellow/Navy" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 7500,
        requiresStaffName: true,
      },
      {
        id: "zh731",
        slug: "zh731",
        sku: "ZH731",
        name: "Syzmik Womens Hi Vis Polo",
        categoryId: "hi-vis-essentials",
        description: "Class D/N rated women's fit hi-vis polo. Shaped cut, moisture management fabric, vented back. Staff name embroidered on chest.",
        image: "/edge-city/syzmik-hi-vis-zh731.png",
        sizes: ["8", "10", "12", "14", "16", "18", "20", "22", "24"],
        colours: [
            { name: "Yellow/Navy" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 6500,
        requiresStaffName: true,
      },
    ],
  },
  {
    id: "tees-polos",
    slug: "tees-polos",
    name: "Tees & Polos",
    description: "Core workwear tees and polos. Comfortable for long days on site.",
    image: "/edge-city/fashion-biz-p200ms-hero.png",
    products: [
      {
        id: "zh135",
        slug: "zh135",
        sku: "ZH135",
        name: "Streetworx Tee",
        categoryId: "tees-polos",
        description: "Lightweight cotton tee with modern slim fit and longer curved hem. Available in three colourways.",
        image: "/edge-city/syzmik-ZH135-hero.png",
        images: ["/edge-city/syzmik-ZH135-charcoal.png", "/edge-city/syzmik-ZH135-navy.png", "/edge-city/syzmik-ZH135-petrol-blue.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Navy" },
            { name: "Petrol Blue" },
            { name: "Charcoal Marle" },
          ],
        decorationMethod: "Screen Print",
        leadWeeks: [2, 2],
        priceCents: 2800,
        requiresStaffName: false,
      },
      {
        id: "p200ms",
        slug: "p200ms",
        sku: "P200MS",
        name: "Balance Short Sleeve Polo",
        categoryId: "tees-polos",
        description: "100% polyester sports interlock. UPF Rating 50+. 155 GSM. Staff name embroidered on chest.",
        image: "/edge-city/fashion-biz-p200ms-hero.png",
        images: ["/edge-city/fashion-biz-p200ms-navy-white-front.png", "/edge-city/fashion-biz-p200ms-navy-white-back.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Navy/Sky" },
            { name: "Navy/Red" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 5500,
        requiresStaffName: false,
      },
      {
        id: "1321",
        slug: "1321",
        sku: "1321",
        name: "Portsea Polo",
        categoryId: "tees-polos",
        description: "Cotton-back polyester polo. 80% polyester / 20% cotton. 180 GSM. Smart appearance for site or office.",
        image: "/edge-city/portsea-1321-front.png",
        images: ["/edge-city/portsea-1321-back.png", "/edge-city/portsea-1321-slate-black.png"],
        sizes: ["8", "10", "12", "14", "16", "18", "20", "22", "24"],
        colours: [
            { name: "Navy/White" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 5800,
        requiresStaffName: false,
      },
    ],
  },
  {
    id: "site-shorts",
    slug: "site-shorts",
    name: "Site Shorts",
    description: "Cooling stretch shorts with multiple cargo pockets for site work.",
    image: "/edge-city/syzmik-shorts-zs235-khaki.png",
    products: [
      {
        id: "zs235",
        slug: "zs235",
        sku: "ZS235",
        name: "Essential Stretch Cargo Short",
        categoryId: "site-shorts",
        description: "98% Cotton 2% Elastane 280 GSM. Reinforced seat, multiple cargo pockets. Waist sizes in cm.",
        image: "/edge-city/syzmik-shorts-zs235-khaki.png",
        images: ["/edge-city/syzmik-shorts-zs235-navy.png"],
        sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
        colours: [
            { name: "Navy" },
            { name: "Khaki" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 8500,
        requiresStaffName: false,
      },
      {
        id: "zs607",
        slug: "zs607",
        sku: "ZS607",
        name: "Rugged Cooling Stretch Short",
        categoryId: "site-shorts",
        description: "98% Cotton 2% Elastane Square Weave Cotton Ripstop 240 GSM. Superior durability for demanding sites.",
        image: "/edge-city/ZS607-hero.png",
        images: ["/edge-city/ZS607-navy.png", "/edge-city/ZS607-khaki.png", "/edge-city/ZS607-black.png"],
        sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
        colours: [
            { name: "Navy" },
            { name: "Khaki" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 9500,
        requiresStaffName: false,
      },
      {
        id: "zs735",
        slug: "zs735",
        sku: "ZS735",
        name: "Womens Essential Stretch Cargo Short",
        categoryId: "site-shorts",
        description: "Women's cut stretch cargo shorts with cooling vents. Reinforced seat, multiple cargo pockets. Waist in cm.",
        image: "/edge-city/syzmik-shorts-zs735-khaki.png",
        images: ["/edge-city/syzmik-shorts-zs735-navy.png"],
        sizes: ["6", "8", "10", "12", "14", "16", "18", "20", "22", "24"],
        colours: [
            { name: "Khaki" },
            { name: "Navy" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 8500,
        requiresStaffName: false,
      },
    ],
  },
  {
    id: "site-pants",
    slug: "site-pants",
    name: "Site Pants",
    description: "Durable work trousers with full pockets and reinforced wear points.",
    image: "/edge-city/syzmik-shorts-zs235-navy.png",
    products: [
      {
        id: "zp604",
        slug: "zp604",
        sku: "ZP604",
        name: "Rugged Cooling Stretch Pant",
        categoryId: "site-pants",
        description: "98% Cotton 2% Elastane Square Weave Cotton Ripstop 240 GSM. Reinforced knees, multiple pockets, durable seams for tough jobs.",
        image: "/edge-city/syzmik-pants-ZP604-hero.png",
        images: ["/edge-city/syzmik-pants-ZP604-navy.png", "/edge-city/syzmik-pants-ZP604-khaki.png", "/edge-city/syzmik-pants-ZP604-navy-back.png", "/edge-city/syzmik-pants-ZP604-khaki-back.png"],
        sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
        colours: [
            { name: "Navy" },
            { name: "Khaki" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 12800,
        requiresStaffName: false,
      },
      {
        id: "zp444",
        slug: "zp444",
        sku: "ZP444",
        name: "Streetworx Comfort Pant",
        categoryId: "site-pants",
        description: "67% Cotton 31% Polyester 2% Spandex 280 GSM. Contemporary stretch work trousers with room to move.",
        image: "/edge-city/syzmik-pants-ZP444-navy.png",
        images: ["/edge-city/syzmik-pants-ZP444-navy-back.png"],
        sizes: ["72", "77", "82", "87", "92", "97", "102", "107", "112", "117", "122", "127", "132"],
        colours: [
            { name: "Navy" },
          ],
        decorationMethod: "None",
        leadWeeks: [2, 2],
        priceCents: 11500,
        requiresStaffName: false,
      },
    ],
  },
  {
    id: "hoodies-midlayers",
    slug: "hoodies-midlayers",
    name: "Hoodies & Midlayers",
    description: "Weather protection and layering. Keep crews warm and visible on site.",
    image: "/edge-city/syzmik-hoodie-zt467-hero.png",
    products: [
      {
        id: "zt467",
        slug: "zt467",
        sku: "ZT467",
        name: "Multi-Pocket Hoodie",
        categoryId: "hoodies-midlayers",
        description: "55% Cotton 45% Polyester 320 GSM. Hi-vis rated warm hoodie. Multiple pockets, drawstring hood, kangaroo pocket.",
        image: "/edge-city/syzmik-hoodie-zt467-hero.png",
        images: ["/edge-city/syzmik-hoodie-zt467-back.png", "/edge-city/syzmik-hoodie-Charcoal-Black.png", "/edge-city/syzmik-hoodie-Slate-Charcoal.jpeg", "/edge-city/syzmik-hoodie-zt467-navy-charcoal.jpeg"],
        sizes: ["XXS", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Charcoal/Black" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 9500,
        requiresStaffName: true,
      },
      {
        id: "zt867",
        slug: "zt867",
        sku: "ZT867",
        name: "Hi Vis Water Resistant Hoodie",
        categoryId: "hoodies-midlayers",
        description: "100% Polyester Fleece 320 GSM. Segmented reflective tape. Lightweight water resistant shell with warm soft fleece lining.",
        image: "/edge-city/syzmik-hi-vis-zt867.png",
        images: ["/edge-city/syzmik-hi-vis-zt867-front.png"],
        sizes: ["XXS", "XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Yellow" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 9500,
        requiresStaffName: false,
      },
      {
        id: "xth",
        slug: "xth",
        sku: "XTH",
        name: "XT Performance Pullover Hoodie",
        categoryId: "hoodies-midlayers",
        description: "270 GSM 100% polyester performance fabric. Smart site hoodie for project managers and office-to-site transitions.",
        image: "/edge-city/cloke-hoodie-xth-back-aqua-front.png",
        images: ["/edge-city/cloke-hoodie-xth-black-aqua-back.png", "/edge-city/cloke-hoodie-xth-navy-grey.png", "/edge-city/cloke-hoodie-xth-navy-white.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Navy/Grey" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 8000,
        requiresStaffName: false,
      },
    ],
  },
  {
    id: "headwear",
    slug: "headwear",
    name: "Headwear & Accessories",
    description: "Sun, rain, and brand protection. Complete the uniform programme.",
    image: "/edge-city/syzmik-hi-vis-zh320.png",
    products: [
      {
        id: "115740",
        slug: "115740",
        sku: "115740",
        name: "Bondi Bucket Hat",
        categoryId: "headwear",
        description: "Premium cotton twill bucket hat with white trim and sweatband. Embroidered club branding.",
        image: "/edge-city/trends-bucket-115740-3.png",
        images: ["/edge-city/trends-bucket-115740-4.png"],
        sizes: ["One Size"],
        colours: [
            { name: "White Sandwich Trim" },
            { name: "Navy" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 2400,
        requiresStaffName: false,
      },
      {
        id: "126398",
        slug: "126398",
        sku: "126398",
        name: "Faded Trucker Cap",
        categoryId: "headwear",
        description: "Structured five panel trucker hat with stylish faded finish. Embroidered logo on front panel.",
        image: "/edge-city/trends-trucker-126398-2.png",
        images: ["/edge-city/trends-trucker-126398-4.png"],
        sizes: ["One Size"],
        colours: [
            { name: "Navy" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 2200,
        requiresStaffName: false,
      },
      {
        id: "1174",
        slug: "1174",
        sku: "1174",
        name: "Nylon Bucket Hat",
        categoryId: "headwear",
        description: "Nylon wide brim bucket hat. Lightweight and packable. Ideal for sun protection on site.",
        image: "/edge-city/as-colour-1174-hero.png",
        images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png", "/edge-city/as-colour-1174-khaki.png"],
        sizes: ["One Size"],
        colours: [
            { name: "Navy" },
            { name: "Black" },
            { name: "Khaki" },
          ],
        decorationMethod: "Embroidery",
        leadWeeks: [2, 2],
        priceCents: 4800,
        requiresStaffName: false,
      },
    ],
  },
]

export const EDGE_CITY_FEATURED_COLLECTIONS: PortalFeaturedCollection[] = [
  {
    id: "summer-site-essentials",
    title: "Summer Site Essentials",
    subtitle: "Stay visible and cool in the warm months.",
    categorySlug: "hi-vis-essentials",
    productIds: ["zh135","zh239","zh320","zs235","zs607"],
  },
  {
    id: "project-team-uniform",
    title: "Project Team Uniform",
    subtitle: "Complete hi-vis programme for site-wide consistency.",
    categorySlug: "hi-vis-essentials",
    productIds: ["zh320","zh415","zh731","p200ms"],
  },
  {
    id: "winter-site-kit",
    title: "Layer Up: Winter Ready",
    subtitle: "Weather protection from hi-vis to warm fleece.",
    categorySlug: "hoodies-midlayers",
    productIds: ["zp604","zp444","zt467","zt867"],
  },
  {
    id: "project-manager-kit",
    title: "Project Manager Kit",
    subtitle: "Smart workwear for the office-to-site transition.",
    categorySlug: "tees-polos",
    productIds: ["xth"],
  },
]
