import type { ClientPortalConfig } from '../types'

const EDGE_CITY: ClientPortalConfig = {
  slug: 'edge-city',
  clientName: 'Edge City Builders',
  portalTitle: 'Staff Uniform Portal',

  logo: {
    type: 'image',
    src: '/edge-city-logo.png',
    alt: 'Edge City',
  },
  accentColor: '#f5a623',
  hero: {
    tagline: 'Your uniform programme.',
    subtitle: 'Order approved staff kit — simple, fast, controlled.',
  },

  brandStory: {
    headline: 'Built for the Site. Built to Last.',
    body: 'Every piece in the Edge City programme is engineered for construction—durable fabrics, high-visibility standards, and a fit that works for real jobs. From early site walks to final handovers, we keep your crew visible, comfortable, and professional.',
    pillars: [
      {
        title: 'Built for the Site',
        description: 'High-vis rated, reinforced seams, weather protection. Every item meets NZ work standards.',
      },
      {
        title: 'One Programme All Roles',
        description: 'Site managers, trades, admin. One ordering system fits every member of your team.',
      },
      {
        title: 'Ordered in Minutes',
        description: 'Pre-approved stock. Fast turnaround. No procurement headaches.',
      },
    ],
  },

  categories: [
    {
      id: 'hi-vis-essentials',
      slug: 'hi-vis-essentials',
      name: 'Hi-Vis Essentials',
      description: 'Class D/N rated high-visibility wear. Meet site safety standards on day one.',
      image: '/edge-city/syzmik-hi-vis-zh320.png',
      products: [
        {
          id: 'zh135',
          slug: 'zh135',
          name: 'Syzmik Hi Vis Vest',
          categoryId: 'hi-vis-essentials',
          description: 'Class D/N rated hi-vis safety vest. Lightweight, packable, meets all regulatory standards.',
          image: '/edge-city/syzmik-hi-vis-zh320.png', // PLACEHOLDER: Replace with actual ZH135 vest image
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'None',
          leadWeeks: [2, 3],
          priceCents: 3500,
          requiresStaffName: false,
          sku: 'ZH135',
        },
        {
          id: 'zh239',
          slug: 'zh239',
          name: 'Syzmik Hi Vis Long Sleeve Shirt',
          categoryId: 'hi-vis-essentials',
          description: 'Class D/N rated hi-vis long-sleeve work shirt. Moisture-wicking, UV protective, vented back.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 7200,
          requiresStaffName: true,
          sku: 'ZH239',
        },
        {
          id: 'zh320',
          slug: 'zh320',
          name: 'Syzmik Hi Vis Polo',
          categoryId: 'hi-vis-essentials',
          description:
            'Class D/N rated hi-vis polo. Moisture management fabric, taped seams, vented back. Staff name embroidered on chest.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 6500,
          requiresStaffName: true,
          sku: 'ZH320',
          sizeChart: { type: 'mens', headers: [], rows: [] },
        },
        {
          id: 'zh415',
          slug: 'zh415',
          name: 'Syzmik Hi Vis Spliced Polo',
          categoryId: 'hi-vis-essentials',
          description:
            'Class D/N hi-vis polo with contrast splicing panels. Moisture management, underarm gussets for full mobility. Staff name embroidered on chest.',
          image: '/edge-city/syzmik-hi-vis-zh415.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh415.png' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 7500,
          requiresStaffName: true,
          sku: 'ZH415',
          sizeChart: { type: 'mens', headers: [], rows: [] },
        },
        {
          id: 'zh731',
          slug: 'zh731',
          name: "Syzmik Women's Hi Vis Polo",
          categoryId: 'hi-vis-essentials',
          description:
            "Class D/N rated women's fit hi-vis polo. Shaped cut, moisture management fabric, vented back. Staff name embroidered on chest.",
          image: '/edge-city/syzmik-hi-vis-zh731.png',
          sizes: ['8', '10', '12', '14', '16', '18', '20', '22', '24'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh731.png' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 6500,
          requiresStaffName: true,
          sku: 'ZH731',
          sizeChart: { type: 'womens', headers: [], rows: [] },
        },
      ],
    },

    {
      id: 'tees-polos',
      slug: 'tees-polos',
      name: 'Tees & Polos',
      description: 'Core workwear tees and polos. Comfortable for long days on site.',
      image: '/edge-city/syzmik-hi-vis-zh320.png',
      products: [
        {
          id: 'p200ms',
          slug: 'p200ms',
          name: 'Work Tee (Mens)',
          categoryId: 'tees-polos',
          description: 'Durable 100% cotton work tee. Classic fit, reinforced seams. Available in khaki and charcoal.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [
            { name: 'Khaki', image: '/edge-city/syzmik-hi-vis-zh320.png' },
            { name: 'Charcoal', image: '/edge-city/syzmik-hi-vis-zh320.png' },
          ],
          decorationMethod: 'Print or Embroidery',
          leadWeeks: [2, 3],
          priceCents: 2800,
          requiresStaffName: false,
          sku: 'P200MS',
        },
        {
          id: '1321',
          slug: '1321',
          name: "Classic Polo (Women's)",
          categoryId: 'tees-polos',
          description: "Women's cut polo shirt. Moisture-wicking fabric, flattering fit. Perfect for site or office.",
          image: '/edge-city/syzmik-hi-vis-zh731.png',
          sizes: ['8', '10', '12', '14', '16', '18', '20', '22', '24'],
          colours: [
            { name: 'Bottle Green', image: '/edge-city/syzmik-hi-vis-zh731.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zh731.png' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 5200,
          requiresStaffName: false,
          sku: '1321',
        },
      ],
    },

    {
      id: 'site-shorts',
      slug: 'site-shorts',
      name: 'Site Shorts',
      description: 'Cooling stretch shorts with multiple cargo pockets for site work.',
      image: '/edge-city/syzmik-hi-vis-zs235-khaki.png',
      products: [
        {
          id: 'zs235',
          slug: 'zs235',
          name: 'Mens Essential Stretch Cargo Short',
          categoryId: 'site-shorts',
          description:
            'Lightweight stretch fabric with cooling vents. Reinforced seat, multiple cargo pockets. Waist sizes in cm.',
          image: '/edge-city/syzmik-hi-vis-zs235-khaki.png',
          sizes: ['72', '77', '82', '87', '92', '97', '102', '107', '112', '117', '122', '127', '132'],
          colours: [
            { name: 'Khaki', image: '/edge-city/syzmik-hi-vis-zs235-khaki.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zs235-navy.png' },
          ],
          decorationMethod: 'None',
          leadWeeks: [2, 3],
          priceCents: 8500,
          requiresStaffName: false,
          sku: 'ZS235',
          sizeChart: {
            type: 'mens',
            headers: ['72', '77', '82', '87', '92', '97', '102', '107', '112', '117', '122', '127', '132'],
            rows: [
              {
                label: 'Half Waist Stretched (cm)',
                values: ['36.5', '39', '41.5', '44', '46.5', '49', '51.5', '54', '56.5', '59', '61.5', '64', '66.5'],
              },
              {
                label: 'Outer Leg Length (cm)',
                values: ['41.5', '42.4', '43.3', '44.2', '45.1', '46', '46.9', '47.8', '48.7', '49.6', '50.5', '51.4', '52.3'],
              },
            ],
          },
        },
        {
          id: 'zs607',
          slug: 'zs607',
          name: 'Rugged Work Shorts',
          categoryId: 'site-shorts',
          description: 'Heavy-duty cotton/polyester blend shorts with reinforced pockets and durability.',
          image: '/edge-city/syzmik-hi-vis-zs235-navy.png',
          sizes: ['72', '77', '82', '87', '92', '97', '102', '107', '112', '117', '122', '127', '132'],
          colours: [
            { name: 'Black', image: '/edge-city/syzmik-hi-vis-zs235-navy.png' },
            { name: 'Tan', image: '/edge-city/syzmik-hi-vis-zs235-khaki.png' },
          ],
          decorationMethod: 'None',
          leadWeeks: [2, 3],
          priceCents: 9200,
          requiresStaffName: false,
          sku: 'ZS607',
        },
        {
          id: 'zs735',
          slug: 'zs735',
          name: "Women's Essential Stretch Cargo Short",
          categoryId: 'site-shorts',
          description:
            "Women's cut stretch cargo shorts with cooling vents. Reinforced seat, multiple cargo pockets.",
          image: '/edge-city/syzmik-hi-vis-zs735-khaki.png',
          sizes: ['6', '8', '10', '12', '14', '16', '18', '20', '22', '24'],
          colours: [
            { name: 'Khaki', image: '/edge-city/syzmik-hi-vis-zs735-khaki.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zs735-navy.png' },
          ],
          decorationMethod: 'None',
          leadWeeks: [2, 3],
          priceCents: 8500,
          requiresStaffName: false,
          sku: 'ZS735',
          sizeChart: { type: 'womens', headers: [], rows: [] },
        },
      ],
    },

    {
      id: 'site-pants',
      slug: 'site-pants',
      name: 'Site Pants',
      description: 'Durable work trousers with full pockets and reinforced wear points.',
      image: '/edge-city/syzmik-hi-vis-zs235-navy.png',
      products: [
        {
          id: 'zp604',
          slug: 'zp604',
          name: 'Mens Rugged Work Pants',
          categoryId: 'site-pants',
          description:
            'Heavy-duty cotton/polyester blend trousers. Reinforced knees, multiple pockets, durable seams for tough jobs.',
          image: '/edge-city/syzmik-hi-vis-zs235-navy.png',
          sizes: ['72', '77', '82', '87', '92', '97', '102', '107', '112', '117', '122', '127', '132'],
          colours: [
            { name: 'Charcoal', image: '/edge-city/syzmik-hi-vis-zs235-navy.png' },
            { name: 'Khaki', image: '/edge-city/syzmik-hi-vis-zs235-khaki.png' },
          ],
          decorationMethod: 'None',
          leadWeeks: [3, 4],
          priceCents: 12800,
          requiresStaffName: false,
          sku: 'ZP604',
        },
        {
          id: 'zp444',
          slug: 'zp444',
          name: 'Stretch Work Pants',
          categoryId: 'site-pants',
          description:
            'Contemporary stretch work trousers with room to move. UV protection and moisture-wicking for long days.',
          image: '/edge-city/syzmik-hi-vis-zs235-navy.png',
          sizes: ['72', '77', '82', '87', '92', '97', '102', '107', '112', '117', '122', '127', '132'],
          colours: [
            { name: 'Stone', image: '/edge-city/syzmik-hi-vis-zs235-khaki.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zs235-navy.png' },
          ],
          decorationMethod: 'None',
          leadWeeks: [2, 3],
          priceCents: 11500,
          requiresStaffName: false,
          sku: 'ZP444',
        },
      ],
    },

    {
      id: 'hoodies-midlayers',
      slug: 'hoodies-midlayers',
      name: 'Hoodies & Midlayers',
      description: 'Weather protection and layering. Keep crews warm and visible on site.',
      image: '/edge-city/syzmik-hi-vis-zh320.png',
      products: [
        {
          id: 'zt467',
          slug: 'zt467',
          name: 'Hi Vis Hoodie',
          categoryId: 'hoodies-midlayers',
          description:
            'Class D/N rated hi-vis hoodie. Warm fleece lining, drawstring hood, kangaroo pocket. Staff name on chest.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'Embroidery',
          leadWeeks: [4, 5],
          priceCents: 9500,
          requiresStaffName: true,
          sku: 'ZT467',
        },
        {
          id: 'zt867',
          slug: 'zt867',
          name: 'Microfleece Mid-Layer',
          categoryId: 'hoodies-midlayers',
          description:
            'Lightweight microfleece with water resistance. Fits under hi-vis or worn solo. Perfect for layering.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'],
          colours: [
            { name: 'Black', image: '/edge-city/syzmik-hi-vis-zh320.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [3, 4],
          priceCents: 6800,
          requiresStaffName: false,
          sku: 'ZT867',
        },
      ],
    },

    {
      id: 'headwear',
      slug: 'headwear',
      name: 'Headwear & Accessories',
      description: 'Sun, rain, and brand protection. Complete the uniform programme.',
      image: '/edge-city/syzmik-hi-vis-zh320.png',
      products: [
        {
          id: '115740',
          slug: '115740',
          name: 'Site Cap',
          categoryId: 'headwear',
          description:
            'Classic structured cap with embroidered branding. 100% cotton twill, adjustable back strap.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['One Size'],
          colours: [
            { name: 'Khaki', image: '/edge-city/syzmik-hi-vis-zh320.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [2, 3],
          priceCents: 2400,
          requiresStaffName: false,
          sku: '115740',
        },
        {
          id: '126398',
          slug: '126398',
          name: 'Beanie',
          categoryId: 'headwear',
          description: 'Warm knit beanie with fleece lining. Perfect for winter layering and bad weather.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['One Size'],
          colours: [
            { name: 'Black', image: '/edge-city/syzmik-hi-vis-zh320.png' },
            { name: 'Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' },
          ],
          decorationMethod: 'Embroidery',
          leadWeeks: [2, 3],
          priceCents: 1800,
          requiresStaffName: false,
          sku: '126398',
        },
        {
          id: '1174',
          slug: '1174',
          name: 'Work Gloves',
          categoryId: 'headwear',
          description: 'Safety work gloves with grip palm. Suitable for general site work and handling materials.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['S/M', 'M/L', 'L/XL', 'XL/2XL'],
          colours: [{ name: 'Grey/Black', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'None',
          leadWeeks: [1, 2],
          priceCents: 1200,
          requiresStaffName: false,
          sku: '1174',
        },
        {
          id: 'xth',
          slug: 'xth',
          name: 'Hi Vis Safety Vest',
          categoryId: 'headwear',
          description: 'Compact high-visibility safety vest. Class C rated, lightweight and packable.',
          image: '/edge-city/syzmik-hi-vis-zh320.png',
          sizes: ['One Size'],
          colours: [{ name: 'Yellow/Navy', image: '/edge-city/syzmik-hi-vis-zh320.png' }],
          decorationMethod: 'None',
          leadWeeks: [1, 2],
          priceCents: 1600,
          requiresStaffName: false,
          sku: 'XTH',
        },
      ],
    },
  ],

  featuredCollections: [
    {
      id: 'summer-essentials',
      title: 'Summer Site Essentials',
      subtitle: 'Stay visible and cool in the warm months.',
      categorySlug: 'hi-vis-essentials',
      productIds: ['zh320', 'zs235', 'zs607'],
    },
    {
      id: 'winter-layering',
      title: 'Layer Up: Winter Ready',
      subtitle: 'Weather protection from high-vis to warm fleece.',
      categorySlug: 'hoodies-midlayers',
      productIds: ['zt467', 'zt867'],
    },
    {
      id: 'project-team',
      title: 'Project Team Uniform',
      subtitle: 'Complete hi-vis programme for site-wide consistency.',
      categorySlug: 'hi-vis-essentials',
      productIds: ['zh320', 'zh415', 'zh731'],
    },
  ],

  ordering: {
    requiresStaffName: false,
    requiresDeliveryAddress: false,
    deliveryOptions: [
      {
        id: 'head-office',
        label: 'Head Office — Auckland CBD',
        address: '1 Main St, Auckland, 1010',
      },
      {
        id: 'south-site',
        label: 'South Site — Manukau',
        address: '45 Industry Rd, Manukau, 2104',
      },
    ],
    orderNote:
      'All items are pre-approved. Orders are processed within 2 business days. For urgent requests contact your Tendencies account manager.',
  },

  contact: {
    manager: 'Ben',
    email: 'ben@tendencies.co.nz',
    phone: '+64 21 XXX XXXX',
  },

  emails: {
    internalTo: 'ben@tendencies.co.nz',
  },
}

export default EDGE_CITY
