// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED — do not edit by hand.
// Run: npm run import:hirepool
// Source: data/hirepool-products.csv (or .xlsx)
//         data/hirepool-order-history.csv (or .xlsx)
// Generated: 2026-05-17T01:28:08.031Z
// ─────────────────────────────────────────────────────────────────────────────

import type { PortalCategory, PortalProduct, PortalFeaturedCollection } from '../types'

export const HIREPOOL_PRODUCTS: PortalProduct[] = [
  {
    id: "hp-polo-01",
    slug: "hp-polo-01",
    sku: "HP-POLO-01",
    name: "Branch Polo",
    categoryId: "staff-apparel",
    description: "The core Hirepool uniform polo. Moisture-wicking performance fabric, embroidered chest logo, available in orange and charcoal. Suitable for counter, yard, and customer-facing roles.",
    image: "/edge-city/fashion-biz-p200ms-hero.png",
    images: ["/edge-city/fashion-biz-p200ms-navy-white-front.png", "/edge-city/fashion-biz-p200ms-navy-white-back.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Hirepool Orange" },
        { name: "Charcoal" },
        { name: "Black" },
      ],
    decorationMethod: "Embroidery — chest logo + optional name",
    leadWeeks: [4, 6],
    priceCents: 5200,
    requiresStaffName: false,
    moq: 12,
    material: "Moisture-wicking polyester performance fabric",
    tags: ["polo","uniform","staff","branch","counter"],
    orderHistory: [
      { orderRef: "HP-2024-001", date: "2024-03-15", qty: 48, unitPriceCents: 5200, totalCents: 249600, client: "Hirepool Ltd", notes: "Branch rollout — Auckland North region. 12 branches x 4 polos." },
      { orderRef: "HP-2025-003", date: "2025-07-01", qty: 24, unitPriceCents: 5200, totalCents: 124800, client: "Hirepool Ltd", notes: "Mid-year top-up — replacement polos for wear." },
    ],
  },
  {
    id: "hp-tee-01",
    slug: "hp-tee-01",
    sku: "HP-TEE-01",
    name: "Staff Tee",
    categoryId: "staff-apparel",
    description: "Heavyweight 240gsm cotton tee. A step up from a standard promo shirt — holds its shape, holds a print, and gets worn outside of work. Suitable for yard staff, trade events, and internal merch.",
    image: "/edge-city/as-colour-1174-hero.png",
    images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png", "/edge-city/as-colour-1174-khaki.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Black" },
        { name: "Navy" },
        { name: "Stone" },
      ],
    decorationMethod: "Screen-print or DTF — front chest + back option",
    leadWeeks: [3, 5],
    priceCents: 3800,
    requiresStaffName: false,
    moq: 12,
    material: "240gsm 100% cotton",
    tags: ["tee","t-shirt","staff","yard","event","merch"],
    orderHistory: [
      { orderRef: "HP-2024-002", date: "2024-06-20", qty: 60, unitPriceCents: 3800, totalCents: 228000, client: "Hirepool Ltd", notes: "Staff tee top-up for summer. Nationwide." },
    ],
  },
  {
    id: "hp-hoodie-01",
    slug: "hp-hoodie-01",
    sku: "HP-HOODIE-01",
    name: "Team Hoodie",
    categoryId: "staff-apparel",
    description: "Midweight brushed-back fleece hoodie. Embroidered chest logo and optional department/branch print on back. Works across site, office, and off-field — the item staff keep.",
    image: "/edge-city/syzmik-hoodie-zt467-hero.png",
    images: ["/edge-city/syzmik-hoodie-zt467-back.png", "/edge-city/syzmik-hoodie-Charcoal-Black.png", "/edge-city/syzmik-hoodie-Slate-Charcoal.jpeg"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Black / Charcoal" },
        { name: "Slate / Charcoal" },
        { name: "Navy / Charcoal" },
      ],
    decorationMethod: "Embroidery — chest logo. Optional back print.",
    leadWeeks: [5, 7],
    priceCents: 8900,
    requiresStaffName: false,
    moq: 12,
    material: "Midweight brushed-back fleece",
    tags: ["hoodie","fleece","midlayer","staff","office","site"],
    orderHistory: [
      { orderRef: "HP-2025-001", date: "2025-02-14", qty: 40, unitPriceCents: 8900, totalCents: 356000, client: "Hirepool Ltd", notes: "Winter layering programme — nationwide branch issue." },
    ],
  },
  {
    id: "hp-cap-01",
    slug: "hp-cap-01",
    sku: "HP-CAP-01",
    name: "Branded Cap",
    categoryId: "staff-apparel",
    description: "Six-panel structured cap in heavy cotton twill. Embroidered Hirepool logo to front panel. Available in orange, black, and charcoal.",
    image: "/cat-cap.jpg",
    sizes: ["One size"],
    colours: [
        { name: "Orange" },
        { name: "Black" },
        { name: "Charcoal" },
      ],
    decorationMethod: "Embroidery — front panel",
    leadWeeks: [4, 6],
    priceCents: 4200,
    requiresStaffName: false,
    moq: 12,
    material: "Heavy cotton twill",
    tags: ["cap","hat","headwear","staff","uniform"],
    orderHistory: [
      { orderRef: "HP-2024-001", date: "2024-03-15", qty: 48, unitPriceCents: 4200, totalCents: 201600, client: "Hirepool Ltd", notes: "Same branch rollout order — caps to match." },
      { orderRef: "HP-2025-003", date: "2025-07-01", qty: 24, unitPriceCents: 4200, totalCents: 100800, client: "Hirepool Ltd", notes: "Cap top-up to match polo order." },
    ],
  },
  {
    id: "hp-hv-vest-01",
    slug: "hp-hv-vest-01",
    sku: "HP-HV-VEST-01",
    name: "Hi-Vis Vest",
    categoryId: "safety-hi-vis",
    description: "Class D day/night rated safety vest. Hirepool logo screen-printed to back. Lightweight, breathable mesh back, solid front panel. The standard site vest for visiting crews and contractors.",
    image: "/edge-city/syzmik-hi-vis-ZH239-hero.png",
    images: ["/edge-city/syzmik-hi-vis-ZH239-front.png", "/edge-city/syzmik-hi-vis-ZH239-back.png"],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colours: [
        { name: "Orange" },
        { name: "Yellow" },
      ],
    decorationMethod: "Screen-print — back panel (logo + optional text)",
    leadWeeks: [2, 4],
    priceCents: 3600,
    requiresStaffName: false,
    moq: 20,
    material: "Polyester mesh and solid fabric, Class D rated",
    tags: ["hi-vis","vest","safety","site","yard","class-d","compliance"],
    orderHistory: [
      { orderRef: "HP-2024-001", date: "2024-03-15", qty: 96, unitPriceCents: 3600, totalCents: 345600, client: "Hirepool Ltd", notes: "Same branch rollout — 8 vests per branch." },
      { orderRef: "HP-2025-001", date: "2025-02-14", qty: 50, unitPriceCents: 3600, totalCents: 180000, client: "Hirepool Ltd", notes: "Additional vests for new yard hires." },
    ],
  },
  {
    id: "hp-hv-shirt-01",
    slug: "hp-hv-shirt-01",
    sku: "HP-HV-SHIRT-01",
    name: "Hi-Vis Long Sleeve Shirt",
    categoryId: "safety-hi-vis",
    description: "Lightweight cotton/poly blend hi-vis shirt. Two chest pockets, contrast tape shoulder-to-wrist. Embroidered logo to left chest. Suitable for branch and site operations year-round.",
    image: "/edge-city/syzmik-hi-vis-zh320-hero.png",
    images: ["/edge-city/syzmik-hi-vis-zh320-front.png", "/edge-city/syzmik-hi-vis-zh320-back.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    colours: [
        { name: "Orange" },
        { name: "Yellow" },
      ],
    decorationMethod: "Embroidery — left chest logo",
    leadWeeks: [3, 5],
    priceCents: 6500,
    requiresStaffName: false,
    moq: 12,
    material: "Cotton/polyester blend with reflective tape",
    tags: ["hi-vis","shirt","long-sleeve","safety","site","branch"],
    orderHistory: [
      { orderRef: "HP-2024-003", date: "2024-09-10", qty: 36, unitPriceCents: 6500, totalCents: 234000, client: "Hirepool Ltd", notes: "Site operations refresh — yard and depot staff." },
    ],
  },
  {
    id: "hp-hv-polo-01",
    slug: "hp-hv-polo-01",
    sku: "HP-HV-POLO-01",
    name: "Hi-Vis Polo",
    categoryId: "safety-hi-vis",
    description: "Hi-vis rated polo for customer-facing site and branch staff. Performance fabric with contrast reflective tape. Presents well in front of customers while meeting site requirements.",
    image: "/edge-city/syzmik-hi-vis-zt867-front.png",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Orange / Navy" },
        { name: "Yellow / Navy" },
      ],
    decorationMethod: "Embroidery — left chest logo",
    leadWeeks: [3, 5],
    priceCents: 5800,
    requiresStaffName: false,
    moq: 12,
    material: "Performance polyester with contrast reflective tape",
    tags: ["hi-vis","polo","safety","counter","customer-facing","branch"],
  },
  {
    id: "hp-kit-branch-01",
    slug: "hp-kit-branch-01",
    sku: "HP-KIT-BRANCH-01",
    name: "New Branch Opening Kit",
    categoryId: "branch-kits",
    description: "A curated starter kit for a new Hirepool branch opening. Includes branded polo (x4), staff tee (x4), hi-vis vest (x6), and branded cap (x4) — pre-decorated with Hirepool branding and ready to unbox. Quantity and styles are customisable per branch headcount.",
    image: "/edge-city/placeholder.png",
    sizes: ["Kit — sizes specified at order"],
    colours: [
        { name: "Hirepool standard" },
      ],
    decorationMethod: "Per-item decoration as specified in kit",
    leadWeeks: [5, 7],
    priceCents: 18500,
    requiresStaffName: false,
    moq: 1,
    material: "Mixed — per items in kit",
    tags: ["kit","branch","opening","polo","tee","hi-vis","cap"],
  },
  {
    id: "hp-kit-counter-01",
    slug: "hp-kit-counter-01",
    sku: "HP-KIT-COUNTER-01",
    name: "Counter Essentials Kit",
    categoryId: "branch-kits",
    description: "Smaller kit designed for counter and customer-facing staff at existing branches. Includes branded polo (x2), staff tee (x2), and cap (x2). Ideal for top-ups when new staff join or existing kit wears out.",
    image: "/edge-city/placeholder.png",
    sizes: ["Kit — sizes specified at order"],
    colours: [
        { name: "Hirepool standard" },
      ],
    decorationMethod: "Per-item decoration as specified in kit",
    leadWeeks: [4, 6],
    priceCents: 14000,
    requiresStaffName: false,
    moq: 1,
    material: "Mixed — per items in kit",
    tags: ["kit","counter","staff","polo","tee","cap","top-up"],
  },
  {
    id: "hp-pack-trade-01",
    slug: "hp-pack-trade-01",
    sku: "HP-PACK-TRADE-01",
    name: "Trade Account Welcome Pack",
    categoryId: "trade-packs",
    description: "A curated branded pack for new or high-value trade account customers. Includes a branded tee, cap, and insulated bottle — items that get used on-site and keep Hirepool visible beyond the transaction. Packaged in a branded cotton tote.",
    image: "/edge-city/placeholder.png",
    sizes: ["One size (tee sizing captured at fulfilment)"],
    colours: [
        { name: "Hirepool orange" },
      ],
    decorationMethod: "Screen-print (tee) · Embroidery (cap) · Laser-etch (bottle)",
    leadWeeks: [4, 6],
    priceCents: 8500,
    requiresStaffName: false,
    moq: 10,
    material: "Mixed — tee / cap / bottle / tote",
    tags: ["trade","pack","welcome","customer","bottle","tote","key-account"],
    orderHistory: [
      { orderRef: "HP-2024-004", date: "2024-11-01", qty: 25, unitPriceCents: 8500, totalCents: 212500, client: "Hirepool Ltd", notes: "Trade account welcome packs for key account drive Q4." },
    ],
  },
  {
    id: "hp-pack-contractor-01",
    slug: "hp-pack-contractor-01",
    sku: "HP-PACK-CONTRACTOR-01",
    name: "Contractor Pack",
    categoryId: "trade-packs",
    description: "A safety-oriented branded pack for contractors working on or around Hirepool equipment. Includes a hi-vis vest (Hirepool-branded back), cap, and branded notebook. Reinforces safe-use messaging while putting Hirepool branding on-site.",
    image: "/edge-city/placeholder.png",
    sizes: ["One size (vest sizing S-5XL specified at order)"],
    colours: [
        { name: "Safety orange" },
      ],
    decorationMethod: "Screen-print (vest) · Embroidery (cap) · Deboss (notebook)",
    leadWeeks: [4, 6],
    priceCents: 7200,
    requiresStaffName: false,
    moq: 10,
    material: "Mixed — vest / cap / notebook",
    tags: ["contractor","pack","hi-vis","safety","notebook","site"],
  },
  {
    id: "hp-event-tee-01",
    slug: "hp-event-tee-01",
    sku: "HP-EVENT-TEE-01",
    name: "Event Tee",
    categoryId: "event-campaign",
    description: "A campaign-specific tee for trade days, expos, and activation events. Heavier-weight than a standard promo shirt — people keep it. Available in quick turnaround from approved Hirepool artwork.",
    image: "/edge-city/as-colour-1174-hero.png",
    images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colours: [
        { name: "Black" },
        { name: "Navy" },
        { name: "Orange" },
      ],
    decorationMethod: "Screen-print or DTF — front and/or back",
    leadWeeks: [2, 4],
    priceCents: 3800,
    requiresStaffName: false,
    moq: 25,
    material: "200gsm cotton/poly blend",
    tags: ["tee","event","trade-day","campaign","expo","activation"],
    orderHistory: [
      { orderRef: "HP-2025-002", date: "2025-04-22", qty: 150, unitPriceCents: 3800, totalCents: 570000, client: "Hirepool Ltd", notes: "Fieldays 2025 activation — campaign print front and back." },
    ],
  },
  {
    id: "hp-pack-campaign-01",
    slug: "hp-pack-campaign-01",
    sku: "HP-PACK-CAMPAIGN-01",
    name: "Safety Campaign Pack",
    categoryId: "event-campaign",
    description: "A bundled safety campaign pack for seasonal or compliance-driven pushes. Configurable contents — typically a hi-vis vest, printed tote, and campaign-specific notebook or printed card. Minimum 50 packs. Easily reordered with updated artwork each season.",
    image: "/edge-city/placeholder.png",
    sizes: ["One size pack"],
    colours: [
        { name: "Campaign-specific" },
      ],
    decorationMethod: "Per-item — screen-print, pad-print, or laser-etch",
    leadWeeks: [4, 6],
    priceCents: 9500,
    requiresStaffName: false,
    moq: 50,
    material: "Mixed — vest / tote / notebook",
    tags: ["safety","campaign","pack","hi-vis","tote","notebook","seasonal","compliance"],
  },
]

export const HIREPOOL_CATEGORIES: PortalCategory[] = [
  {
    id: "staff-apparel",
    slug: "staff-apparel",
    name: "Staff Apparel",
    description: "Everyday branded apparel for branch teams — polos, tees, hoodies, and caps in approved Hirepool styles.",
    image: "/edge-city/fashion-biz-p200ms-hero.png",
    products: [
      {
        id: "hp-polo-01",
        slug: "hp-polo-01",
        sku: "HP-POLO-01",
        name: "Branch Polo",
        categoryId: "staff-apparel",
        description: "The core Hirepool uniform polo. Moisture-wicking performance fabric, embroidered chest logo, available in orange and charcoal. Suitable for counter, yard, and customer-facing roles.",
        image: "/edge-city/fashion-biz-p200ms-hero.png",
        images: ["/edge-city/fashion-biz-p200ms-navy-white-front.png", "/edge-city/fashion-biz-p200ms-navy-white-back.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Hirepool Orange" },
            { name: "Charcoal" },
            { name: "Black" },
          ],
        decorationMethod: "Embroidery — chest logo + optional name",
        leadWeeks: [4, 6],
        priceCents: 5200,
        requiresStaffName: false,
        moq: 12,
        material: "Moisture-wicking polyester performance fabric",
        tags: ["polo","uniform","staff","branch","counter"],
        orderHistory: [
          { orderRef: "HP-2024-001", date: "2024-03-15", qty: 48, unitPriceCents: 5200, totalCents: 249600, client: "Hirepool Ltd", notes: "Branch rollout — Auckland North region. 12 branches x 4 polos." },
          { orderRef: "HP-2025-003", date: "2025-07-01", qty: 24, unitPriceCents: 5200, totalCents: 124800, client: "Hirepool Ltd", notes: "Mid-year top-up — replacement polos for wear." },
        ],
      },
      {
        id: "hp-tee-01",
        slug: "hp-tee-01",
        sku: "HP-TEE-01",
        name: "Staff Tee",
        categoryId: "staff-apparel",
        description: "Heavyweight 240gsm cotton tee. A step up from a standard promo shirt — holds its shape, holds a print, and gets worn outside of work. Suitable for yard staff, trade events, and internal merch.",
        image: "/edge-city/as-colour-1174-hero.png",
        images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png", "/edge-city/as-colour-1174-khaki.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Black" },
            { name: "Navy" },
            { name: "Stone" },
          ],
        decorationMethod: "Screen-print or DTF — front chest + back option",
        leadWeeks: [3, 5],
        priceCents: 3800,
        requiresStaffName: false,
        moq: 12,
        material: "240gsm 100% cotton",
        tags: ["tee","t-shirt","staff","yard","event","merch"],
        orderHistory: [
          { orderRef: "HP-2024-002", date: "2024-06-20", qty: 60, unitPriceCents: 3800, totalCents: 228000, client: "Hirepool Ltd", notes: "Staff tee top-up for summer. Nationwide." },
        ],
      },
      {
        id: "hp-hoodie-01",
        slug: "hp-hoodie-01",
        sku: "HP-HOODIE-01",
        name: "Team Hoodie",
        categoryId: "staff-apparel",
        description: "Midweight brushed-back fleece hoodie. Embroidered chest logo and optional department/branch print on back. Works across site, office, and off-field — the item staff keep.",
        image: "/edge-city/syzmik-hoodie-zt467-hero.png",
        images: ["/edge-city/syzmik-hoodie-zt467-back.png", "/edge-city/syzmik-hoodie-Charcoal-Black.png", "/edge-city/syzmik-hoodie-Slate-Charcoal.jpeg"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Black / Charcoal" },
            { name: "Slate / Charcoal" },
            { name: "Navy / Charcoal" },
          ],
        decorationMethod: "Embroidery — chest logo. Optional back print.",
        leadWeeks: [5, 7],
        priceCents: 8900,
        requiresStaffName: false,
        moq: 12,
        material: "Midweight brushed-back fleece",
        tags: ["hoodie","fleece","midlayer","staff","office","site"],
        orderHistory: [
          { orderRef: "HP-2025-001", date: "2025-02-14", qty: 40, unitPriceCents: 8900, totalCents: 356000, client: "Hirepool Ltd", notes: "Winter layering programme — nationwide branch issue." },
        ],
      },
      {
        id: "hp-cap-01",
        slug: "hp-cap-01",
        sku: "HP-CAP-01",
        name: "Branded Cap",
        categoryId: "staff-apparel",
        description: "Six-panel structured cap in heavy cotton twill. Embroidered Hirepool logo to front panel. Available in orange, black, and charcoal.",
        image: "/cat-cap.jpg",
        sizes: ["One size"],
        colours: [
            { name: "Orange" },
            { name: "Black" },
            { name: "Charcoal" },
          ],
        decorationMethod: "Embroidery — front panel",
        leadWeeks: [4, 6],
        priceCents: 4200,
        requiresStaffName: false,
        moq: 12,
        material: "Heavy cotton twill",
        tags: ["cap","hat","headwear","staff","uniform"],
        orderHistory: [
          { orderRef: "HP-2024-001", date: "2024-03-15", qty: 48, unitPriceCents: 4200, totalCents: 201600, client: "Hirepool Ltd", notes: "Same branch rollout order — caps to match." },
          { orderRef: "HP-2025-003", date: "2025-07-01", qty: 24, unitPriceCents: 4200, totalCents: 100800, client: "Hirepool Ltd", notes: "Cap top-up to match polo order." },
        ],
      },
    ],
  },
  {
    id: "safety-hi-vis",
    slug: "safety-hi-vis",
    name: "Safety & Hi-Vis",
    description: "Hi-vis rated apparel for site teams, yard operations, and compliance-required roles. All items meet AS/NZS standards.",
    image: "/edge-city/syzmik-hi-vis-ZH239-hero.png",
    products: [
      {
        id: "hp-hv-vest-01",
        slug: "hp-hv-vest-01",
        sku: "HP-HV-VEST-01",
        name: "Hi-Vis Vest",
        categoryId: "safety-hi-vis",
        description: "Class D day/night rated safety vest. Hirepool logo screen-printed to back. Lightweight, breathable mesh back, solid front panel. The standard site vest for visiting crews and contractors.",
        image: "/edge-city/syzmik-hi-vis-ZH239-hero.png",
        images: ["/edge-city/syzmik-hi-vis-ZH239-front.png", "/edge-city/syzmik-hi-vis-ZH239-back.png"],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
        colours: [
            { name: "Orange" },
            { name: "Yellow" },
          ],
        decorationMethod: "Screen-print — back panel (logo + optional text)",
        leadWeeks: [2, 4],
        priceCents: 3600,
        requiresStaffName: false,
        moq: 20,
        material: "Polyester mesh and solid fabric, Class D rated",
        tags: ["hi-vis","vest","safety","site","yard","class-d","compliance"],
        orderHistory: [
          { orderRef: "HP-2024-001", date: "2024-03-15", qty: 96, unitPriceCents: 3600, totalCents: 345600, client: "Hirepool Ltd", notes: "Same branch rollout — 8 vests per branch." },
          { orderRef: "HP-2025-001", date: "2025-02-14", qty: 50, unitPriceCents: 3600, totalCents: 180000, client: "Hirepool Ltd", notes: "Additional vests for new yard hires." },
        ],
      },
      {
        id: "hp-hv-shirt-01",
        slug: "hp-hv-shirt-01",
        sku: "HP-HV-SHIRT-01",
        name: "Hi-Vis Long Sleeve Shirt",
        categoryId: "safety-hi-vis",
        description: "Lightweight cotton/poly blend hi-vis shirt. Two chest pockets, contrast tape shoulder-to-wrist. Embroidered logo to left chest. Suitable for branch and site operations year-round.",
        image: "/edge-city/syzmik-hi-vis-zh320-hero.png",
        images: ["/edge-city/syzmik-hi-vis-zh320-front.png", "/edge-city/syzmik-hi-vis-zh320-back.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
        colours: [
            { name: "Orange" },
            { name: "Yellow" },
          ],
        decorationMethod: "Embroidery — left chest logo",
        leadWeeks: [3, 5],
        priceCents: 6500,
        requiresStaffName: false,
        moq: 12,
        material: "Cotton/polyester blend with reflective tape",
        tags: ["hi-vis","shirt","long-sleeve","safety","site","branch"],
        orderHistory: [
          { orderRef: "HP-2024-003", date: "2024-09-10", qty: 36, unitPriceCents: 6500, totalCents: 234000, client: "Hirepool Ltd", notes: "Site operations refresh — yard and depot staff." },
        ],
      },
      {
        id: "hp-hv-polo-01",
        slug: "hp-hv-polo-01",
        sku: "HP-HV-POLO-01",
        name: "Hi-Vis Polo",
        categoryId: "safety-hi-vis",
        description: "Hi-vis rated polo for customer-facing site and branch staff. Performance fabric with contrast reflective tape. Presents well in front of customers while meeting site requirements.",
        image: "/edge-city/syzmik-hi-vis-zt867-front.png",
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Orange / Navy" },
            { name: "Yellow / Navy" },
          ],
        decorationMethod: "Embroidery — left chest logo",
        leadWeeks: [3, 5],
        priceCents: 5800,
        requiresStaffName: false,
        moq: 12,
        material: "Performance polyester with contrast reflective tape",
        tags: ["hi-vis","polo","safety","counter","customer-facing","branch"],
      },
    ],
  },
  {
    id: "branch-kits",
    slug: "branch-kits",
    name: "Branch Kits",
    description: "Pre-built kits for new branch openings and branch refreshes. Everything needed to dress a new location consistently from day one.",
    image: "/edge-city/placeholder.png",
    products: [
      {
        id: "hp-kit-branch-01",
        slug: "hp-kit-branch-01",
        sku: "HP-KIT-BRANCH-01",
        name: "New Branch Opening Kit",
        categoryId: "branch-kits",
        description: "A curated starter kit for a new Hirepool branch opening. Includes branded polo (x4), staff tee (x4), hi-vis vest (x6), and branded cap (x4) — pre-decorated with Hirepool branding and ready to unbox. Quantity and styles are customisable per branch headcount.",
        image: "/edge-city/placeholder.png",
        sizes: ["Kit — sizes specified at order"],
        colours: [
            { name: "Hirepool standard" },
          ],
        decorationMethod: "Per-item decoration as specified in kit",
        leadWeeks: [5, 7],
        priceCents: 18500,
        requiresStaffName: false,
        moq: 1,
        material: "Mixed — per items in kit",
        tags: ["kit","branch","opening","polo","tee","hi-vis","cap"],
      },
      {
        id: "hp-kit-counter-01",
        slug: "hp-kit-counter-01",
        sku: "HP-KIT-COUNTER-01",
        name: "Counter Essentials Kit",
        categoryId: "branch-kits",
        description: "Smaller kit designed for counter and customer-facing staff at existing branches. Includes branded polo (x2), staff tee (x2), and cap (x2). Ideal for top-ups when new staff join or existing kit wears out.",
        image: "/edge-city/placeholder.png",
        sizes: ["Kit — sizes specified at order"],
        colours: [
            { name: "Hirepool standard" },
          ],
        decorationMethod: "Per-item decoration as specified in kit",
        leadWeeks: [4, 6],
        priceCents: 14000,
        requiresStaffName: false,
        moq: 1,
        material: "Mixed — per items in kit",
        tags: ["kit","counter","staff","polo","tee","cap","top-up"],
      },
    ],
  },
  {
    id: "trade-packs",
    slug: "trade-packs",
    name: "Trade Packs",
    description: "Branded merchandise packs for trade account customers, contractors, and key accounts. Keeps Hirepool front of mind on the job.",
    image: "/edge-city/placeholder.png",
    products: [
      {
        id: "hp-pack-trade-01",
        slug: "hp-pack-trade-01",
        sku: "HP-PACK-TRADE-01",
        name: "Trade Account Welcome Pack",
        categoryId: "trade-packs",
        description: "A curated branded pack for new or high-value trade account customers. Includes a branded tee, cap, and insulated bottle — items that get used on-site and keep Hirepool visible beyond the transaction. Packaged in a branded cotton tote.",
        image: "/edge-city/placeholder.png",
        sizes: ["One size (tee sizing captured at fulfilment)"],
        colours: [
            { name: "Hirepool orange" },
          ],
        decorationMethod: "Screen-print (tee) · Embroidery (cap) · Laser-etch (bottle)",
        leadWeeks: [4, 6],
        priceCents: 8500,
        requiresStaffName: false,
        moq: 10,
        material: "Mixed — tee / cap / bottle / tote",
        tags: ["trade","pack","welcome","customer","bottle","tote","key-account"],
        orderHistory: [
          { orderRef: "HP-2024-004", date: "2024-11-01", qty: 25, unitPriceCents: 8500, totalCents: 212500, client: "Hirepool Ltd", notes: "Trade account welcome packs for key account drive Q4." },
        ],
      },
      {
        id: "hp-pack-contractor-01",
        slug: "hp-pack-contractor-01",
        sku: "HP-PACK-CONTRACTOR-01",
        name: "Contractor Pack",
        categoryId: "trade-packs",
        description: "A safety-oriented branded pack for contractors working on or around Hirepool equipment. Includes a hi-vis vest (Hirepool-branded back), cap, and branded notebook. Reinforces safe-use messaging while putting Hirepool branding on-site.",
        image: "/edge-city/placeholder.png",
        sizes: ["One size (vest sizing S-5XL specified at order)"],
        colours: [
            { name: "Safety orange" },
          ],
        decorationMethod: "Screen-print (vest) · Embroidery (cap) · Deboss (notebook)",
        leadWeeks: [4, 6],
        priceCents: 7200,
        requiresStaffName: false,
        moq: 10,
        material: "Mixed — vest / cap / notebook",
        tags: ["contractor","pack","hi-vis","safety","notebook","site"],
      },
    ],
  },
  {
    id: "event-campaign",
    slug: "event-campaign",
    name: "Event & Campaign",
    description: "Branded items for trade days, safety campaigns, sponsorships, and seasonal pushes. Flexible formats for short-run and repeat requirements.",
    image: "/edge-city/as-colour-1174-hero.png",
    products: [
      {
        id: "hp-event-tee-01",
        slug: "hp-event-tee-01",
        sku: "HP-EVENT-TEE-01",
        name: "Event Tee",
        categoryId: "event-campaign",
        description: "A campaign-specific tee for trade days, expos, and activation events. Heavier-weight than a standard promo shirt — people keep it. Available in quick turnaround from approved Hirepool artwork.",
        image: "/edge-city/as-colour-1174-hero.png",
        images: ["/edge-city/as-colour-1174-black.png", "/edge-city/as-colour-1174-navy.png"],
        sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
        colours: [
            { name: "Black" },
            { name: "Navy" },
            { name: "Orange" },
          ],
        decorationMethod: "Screen-print or DTF — front and/or back",
        leadWeeks: [2, 4],
        priceCents: 3800,
        requiresStaffName: false,
        moq: 25,
        material: "200gsm cotton/poly blend",
        tags: ["tee","event","trade-day","campaign","expo","activation"],
        orderHistory: [
          { orderRef: "HP-2025-002", date: "2025-04-22", qty: 150, unitPriceCents: 3800, totalCents: 570000, client: "Hirepool Ltd", notes: "Fieldays 2025 activation — campaign print front and back." },
        ],
      },
      {
        id: "hp-pack-campaign-01",
        slug: "hp-pack-campaign-01",
        sku: "HP-PACK-CAMPAIGN-01",
        name: "Safety Campaign Pack",
        categoryId: "event-campaign",
        description: "A bundled safety campaign pack for seasonal or compliance-driven pushes. Configurable contents — typically a hi-vis vest, printed tote, and campaign-specific notebook or printed card. Minimum 50 packs. Easily reordered with updated artwork each season.",
        image: "/edge-city/placeholder.png",
        sizes: ["One size pack"],
        colours: [
            { name: "Campaign-specific" },
          ],
        decorationMethod: "Per-item — screen-print, pad-print, or laser-etch",
        leadWeeks: [4, 6],
        priceCents: 9500,
        requiresStaffName: false,
        moq: 50,
        material: "Mixed — vest / tote / notebook",
        tags: ["safety","campaign","pack","hi-vis","tote","notebook","seasonal","compliance"],
      },
    ],
  },
]

export const HIREPOOL_FEATURED_COLLECTIONS: PortalFeaturedCollection[] = [
  {
    id: "branch-essentials",
    title: "Branch Essentials",
    subtitle: "The core uniform set for every branch — polo, tee, hi-vis, and cap.",
    categorySlug: "staff-apparel",
    productIds: ["hp-polo-01","hp-tee-01","hp-cap-01","hp-hv-vest-01"],
  },
  {
    id: "safety-programme",
    title: "Safety Programme",
    subtitle: "Hi-vis rated apparel for site, yard, and compliance-required roles.",
    categorySlug: "safety-hi-vis",
    productIds: ["hp-hv-vest-01","hp-hv-shirt-01","hp-hv-polo-01"],
  },
  {
    id: "trade-customer",
    title: "Trade & Customer",
    subtitle: "Branded packs for trade account customers and key contractors.",
    categorySlug: "trade-packs",
    productIds: ["hp-pack-trade-01","hp-pack-contractor-01"],
  },
]
